- name: Install packages and binaries (RHEL9 workstation)
  hosts: localhost
  vars:
    user_programs: /usr/local/bin
    el9_packages:
      - ImageMagick
      - bat
      - ffmpeg
      - gcc-c++
      - gnome-tweaks
      - gthumb
      - inotify-tools
      - keepassxc
      - kitty
      - mediainfo
      - optipng
      - pandoc
      - ripgrep
      - shellcheck
      - stow
      - tldr
      - trash-cli
      - xclip
      - xdg-desktop-portal-gnome
      - yt-dlp
      - zathura
      - zathura-bash-completion

  tasks:
    - name: Add the GitHub CLI repository
      become: true
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      args:
        creates: /etc/yum.repos.d/gh-cli.repo

    - name: Add the Flathub repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Add el9 only repositories
      become: true
      when: ansible_facts.distribution != "Fedora"
      block:
        - name: Enable the el9 CodeReady Linux Builder repository
          ansible.builtin.command: dnf config-manager --enable crb
          args:
            creates: /etc/yum.repos.d/*-crb.repo

        - name: Add the Extra Packages for Enterprise Linux repository
          ansible.builtin.dnf:
            name:
              epel-release
            state: present

        - name: Add the el9 RPM Fusion repository
          ansible.builtin.dnf:
            name: "{{ item }}"
            state: present
            disable_gpg_check: true
          loop:
            - https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
            - https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

    # =========================================================================
    # Remove packages
    # =========================================================================
    - name: Remove unwanted desktop apps
      become: true
      ansible.builtin.dnf:
        name:
          - cheese
          - gedit
          - rhythmbox
          - totem
        state: absent

    # =========================================================================
    # Install packages
    # =========================================================================
    - name: Upgrade all packages
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest

    - name: Install el9 packages
      become: true
      ansible.builtin.dnf:
        name: "{{ el9_packages }}"
        state: present

    - name: Install Flatpak packages
      community.general.flatpak:
        name: "{{ flatpak_packages }}"
        state: present

    # =========================================================================
    # Install binaries
    # =========================================================================
    - name: Check packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Refresh font cache
      ansible.builtin.command: fc-cache -vf
      changed_when: false
