"$schema" = 'https://starship.rs/config-schema.json'

format = """
\\[\
$username\
($hostname)\
$directory\
$git_branch\
$git_status\
\\]\
(\\[\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$conda\
$java\
$julia\
$nodejs\
$nim\
$rust\
$docker_context\
\\])\
$character\
"""
# $fill\
# $time\
# $character
# """
# We use the `fill` module instead
right_format = '$time'

# Timeouts
scan_timeout = 50
command_timeout = 500

# Adds a newline after each command
add_newline = true

# Colors
palette = 'kurt'

[palettes.kurt]
login = "#909090"
directory = "#808080"
environment = "#707070"

# Prompt character
[character]
disabled = false
format = '$symbol '
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[!](bold yellow)'
vimcmd_replace_one_symbol = '[](bold yellow)'
vimcmd_replace_symbol = '[](bold yellow)'
vimcmd_visual_symbol = '[](bold yellow)'

# Spacer
[fill]
disabled = false
symbol = '·'
style= 'white'

# Login
[username]
show_always = true
style_user = "white"
style_root = "white"
format = '[$user]($style)'
disabled = false

[hostname]
disabled = false
style = "white"
format = '[@$hostname ]($style)'
ssh_only = false

[localip]
ssh_only = false
disabled = true

[os]
style = "white"
disabled = true

# Location
[directory]
style = "white"
format = "[ $path]($style)"
truncation_length = 6
truncation_symbol = "…/"

[directory.substitutions]
"preferences" = " "
"projects" = " "
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"data" = "󰆼 "
"datasets" = "󰆼 "

# Time
[time]
disabled = false
time_format = "%R %d-%m-%Y"
use_12hr = false
style= 'white'
format = '[$time]($style)'

# Environments
# Currently this is a bit verbose due to limitations of the configuration format
[conda]
disabled = false
symbol = "󱔎 "
style = "white"
format = '[ $symbol$environment ]($style)'

[c]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "white"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "white"
format = '[ on $symbol $branch]($style)'

[git_status]
style = "white"
format = '[\($all_status$ahead_behind\)]($style)'

[golang]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "white"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "white"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "white"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "white"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "white"
format = '[ $symbol ($version) ]($style)'
